### ISSUE TITLE
got error while  installing in kaggel notebook

### ISSUE THREAD

**Issue by rddvsr** [frankkramer-lab/MIScnn#171]
error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      Traceback (most recent call last):
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_vendor/packaging/requirements.py", line 35, in __init__
          parsed = _parse_requirement(requirement_string)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_vendor/packaging/_parser.py", line 64, in parse_requirement
          return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_vendor/packaging/_parser.py", line 82, in _parse_requirement
          url, specifier, marker = _parse_requirement_details(tokenizer)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_vendor/packaging/_parser.py", line 126, in _parse_requirement_details
          marker = _parse_requirement_marker(
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_vendor/packaging/_parser.py", line 147, in _parse_requirement_marker
          tokenizer.raise_syntax_error(
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_vendor/packaging/_tokenizer.py", line 165, in raise_syntax_error
          raise ParserSyntaxError(
      setuptools.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
          python_version>"3.7"
                        ^
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-45gh19lg/tensorflow-gpu_22a3983428a348a1919ec68d10c442d2/setup.py", line 40, in <module>
          setuptools.setup()
        File "/opt/conda/lib/python3.10/site-packages/setuptools/__init__.py", line 102, in setup
          _install_setup_requires(attrs)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/__init__.py", line 73, in _install_setup_requires
          dist.parse_config_files(ignore_option_errors=True)
        File "/opt/conda/lib/python3.10/site-packages/setuptools/dist.py", line 629, in parse_config_files
          self._finalize_requires()
        File "/opt/conda/lib/python3.10/site-packages/setuptools/dist.py", line 364, in _finalize_requires
          self._normalize_requires()
        File "/opt/conda/lib/python3.10/site-packages/setuptools/dist.py", line 379, in _normalize_requires
          self.install_requires = list(map(str, _reqs.parse(install_requires)))
        File "/opt/conda/lib/python3.10/site-packages/setuptools/_vendor/packaging/requirements.py", line 37, in __init__
          raise InvalidRequirement(str(e)) from e
      setuptools.extern.packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)
          python_version>"3.7"
                        ^
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Note: you may need to restart the kernel to use updated packages.

**Comment by ka411** [comment]
Hey! I ran into the same issue and managed to solve it. The error is coming from a malformed install_requires entry in the setup.py file of the package you're trying to install (in this case, probably a custom or forked version of tensorflow-gpu). Specifically, this part:
python_version>"3.7"

is not a valid requirement format. It should be written using an environment marker, like this:
python_version > "3.7"

or better yet, as part of an environment marker in extras, for example:
"some-package; python_version > '3.7'"

How I fixed it:
I downloaded the package manually using:
pip download tensorflow-gpu

Unzipped the .tar.gz file, opened the setup.py, and looked for the install_requires or any dependency line that had python_version>"3.7".

I changed it to:
python_version > "3.7"

Then I re-packaged it with:
python setup.py sdist

And finally installed it using:
pip install ./dist/<your-tar.gz-file>.tar.gz


Alternatively, if you just want to skip all this, I suggest checking if you're using an outdated or forked version of the package. Sometimes the pip install link points to a GitHub repo that hasn’t been maintained.
