### ISSUE TITLE
how to prepare data(kits)

### ISSUE THREAD

**Issue by Iamyourbaba** [frankkramer-lab/MIScnn#35]
>>> model = miscnn.Neural_Network(preprocessor=pp, architecture=unet_standard)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/damu/MIScnn/miscnn/neural_network/model.py", line 73, in __init__
    n_labels=self.classes)
  File "/home/damu/MIScnn/miscnn/neural_network/architecture/unet/standard.py", line 132, in create_model_3D
    self.ba_norm_momentum)
  File "/home/damu/MIScnn/miscnn/neural_network/architecture/unet/standard.py", line 197, in expanding_layer_3D
    padding='same')(input), concatenate_link], axis=4)
  File "/home/damu/anaconda3/envs/temp/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 554, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/damu/anaconda3/envs/temp/lib/python3.7/site-packages/tensorflow/python/keras/layers/convolutional.py", line 1140, in call
    outputs_shape[0], outputs_shape[1] * outputs_shape[2],
TypeError: unsupported operand type(s) for *: 'NoneType' and 'NoneType'

**Comment by muellerdo** [comment]
Hey @Iamyourbaba,

sounds like your are providing a sample with None as image/segmentation?

It is hard to say anything without any question/problem description or reproducible code.
Nearly impossible ;)

I would recommend open up a new issue with a clear description of what you want to do and the problem.

Cheers,
Dominik
