### ISSUE TITLE
Update to TensorFlow 2.X

### ISSUE THREAD

**Issue by muellerdo** [frankkramer-lab/MIScnn#9]
Keras Data Generators are buggy in TensorFlow 2.X.  
Seems like TF pulls one item before starting.  
-> Waiting for official fix.

Example:  
Number of created batches for prediction should be 243 which is working if tested manually.  
Number of predictions resulted from TF are 242.
```
Length MIScnn DataGenerator: 243
Number of batches created by MIScnn DataGenerator: 243

2020-04-03 18:57:20.037300: W tensorflow/core/common_runtime/base_collective_executor.cc:217] BaseCollectiveExecutor::StartAbort Out of range: End of sequence
	 [[{{node IteratorGetNext}}]]
WARNING:tensorflow:Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches (in this case, 243 batches). You may need to use the repeat() function when building your dataset.
Traceback (most recent call last):
  File "miscnn/debugging.py", line 102, in <module>
    test = model.predict(indices_list[88:89], direct_output=True)
  File "/usr/local/lib/python3.6/dist-packages/miscnn-0.28-py3.6.egg/miscnn/neural_network/model.py", line 152, in predict
  File "/home/mudomini/projects/MIScnn/miscnn/processing/preprocessor.py", line 197, in postprocessing
    three_dim=self.data_io.interface.three_dim)
  File "/usr/local/lib/python3.6/dist-packages/miscnn-0.28-py3.6.egg/miscnn/utils/patch_operations.py", line 72, in concat_matrices
  File "/usr/local/lib/python3.6/dist-packages/miscnn-0.28-py3.6.egg/miscnn/utils/patch_operations.py", line 230, in concat_3Dmatrices
IndexError: index 484 is out of bounds for axis 0 with size 484
```

TF issue: https://github.com/tensorflow/tensorflow/issues/31509

Setting a number of steps is not working.

**Comment by muellerdo** [comment]
Trying to work on a minimal example for reproduction

**Comment by muellerdo** [comment]
Resolved by manual iteration over Data Generator and calling predict_on_batch().
